services:
  wishstar:
    image: wishstar:latest
    container_name: wishstar
    hostname: wishstar
    stop_grace_period: 90s
    build:
      context: ./Wishstar
      dockerfile: Dockerfile
    environment:
      SERVER_URL: ${SERVER_URL}
    ports:
      - "${HOST_PORT}:8080"
    volumes:
      - /srv/wishstar/data:/app/app
    restart: unless-stopped